// Assembles README.md from the record and repo files. The masthead is the only art;
// everything below it is plain markdown a reader can copy.
import fs from 'node:fs';
import path from 'node:path';
import { CATEGORIES, longDate } from './facts.mjs';
import { HEADLINE, LEDE } from './panels.mjs';
import { ASSETS, ROOT, esc, read } from './lib.mjs';

export const MARKER = '<!-- generated by scripts/readme/build.mjs. do not edit by hand. -->';
export const SITE = 'https://safeai.watch';

/** Node version the build needs, from Astro's own engines field in the lockfile. */
export function nodeRange() {
  const lock = JSON.parse(read('package-lock.json'));
  const engines = lock.packages?.['node_modules/astro']?.engines?.node;
  if (!engines) throw new Error('package-lock.json has no engines.node for astro; cannot state the Node requirement.');
  const min = /^>=\s*(\d+(?:\.\d+)*)$/.exec(engines.trim());
  return min ? `${min[1]} or later` : engines;
}

/*
 * A bare <picture>, never wrapped in <a>: on repository pages GitHub's sanitizer hoists
 * the <img> out of an <a>-wrapped <picture> and drops every <source>, so readers would
 * only ever get the light, wide variant (verified on the blob view, 2026-10-02).
 */
function pic(base, alt) {
  return `<picture>
<source media="(max-width: 500px) and (prefers-color-scheme: dark)" srcset="${ASSETS}/${base}-narrow-dark.svg">
<source media="(max-width: 500px)" srcset="${ASSETS}/${base}-narrow-light.svg">
<source media="(prefers-color-scheme: dark)" srcset="${ASSETS}/${base}-dark.svg">
<img alt="${esc(alt)}" src="${ASSETS}/${base}-light.svg" width="100%">
</picture>`;
}

/** Entry text is plain prose; escape the characters markdown would act on. */
const md = (s) => String(s).replace(/([\\`*_[\]<>#|])/g, '\\$1');

export function buildReadme(facts) {
  const raw = facts.latest;
  const e = { ...raw, title: md(raw.title), happened: md(raw.happened), evidence: md(raw.evidence), uncertain: md(raw.uncertain), source: md(raw.source) };
  const counts = CATEGORIES.map((c) => `${facts.byCategory[c]} ${c.toLowerCase()}`).join(', ');
  const alt = `${HEADLINE}. ${facts.entries} dated, sourced entries drawn as a burst, one dot per entry: ${counts}. Farther from the centre is newer; dashed rings mark January 1. The record is a selection, so density shows coverage, not frequency.`;
  return `${MARKER}

${pic('masthead', alt)}

**[SafeAI.watch](${SITE})** is a public record of AI safety and security for general readers: research, reported incidents, public warnings and policy responses. ${LEDE.split('. ').slice(1).join('. ')}

The record holds ${facts.entries} entries from ${longDate(facts.first)} to ${longDate(facts.last)} (${counts}), drawn from ${facts.publishers} publishers. It is a selection, not a complete count: the burst above shows what the record covers, so its dense rim is no measure of how often such events happen. Read it on the site: [Latest](${SITE}/latest), [Timeline](${SITE}/timeline), [About](${SITE}/about).

## How an entry reads

Every entry keeps four things apart. The newest one, from ${longDate(e.date)}, filed under ${e.category}:

> **${e.title}**
>
> **What happened.** ${e.happened}
>
> **Evidence.** ${e.evidence}
>
> **Uncertain.** ${e.uncertain}
>
> **Source.** [${e.source}](${e.url})

## Run it locally

Needs Node.js ${nodeRange()}.

\`\`\`bash
npm ci
npm run dev
\`\`\`

The dev server runs at http://localhost:4321. \`npm run build\` writes the static site to \`dist/\`, and \`npm run preview\` serves that build. The build first runs \`npm run film:lint\`, which checks the About page film's script against its facts.

## Add or correct an entry

Entries live in [\`src/data/events.json\`](src/data/events.json). Each one has exactly these keys: \`date\` (the source's publication date, \`YYYY-MM-DD\`), \`category\` (one of ${CATEGORIES.map((c) => `\`"${c}"\``).join(', ')}), \`title\`, \`happened\`, \`evidence\`, \`uncertain\`, \`source\` (publisher and source type, such as "RAND · Research report") and \`url\` (https only). [\`src/data/record.ts\`](src/data/record.ts) checks every entry when the site builds and fails the build on a missing, empty or extra key, an unknown category, a date not written as \`YYYY-MM-DD\`, or a link that is not https. Run \`npm run build\` to check a change; CI runs the same build on every pull request.

The art above is generated from the same file. After changing the record, run \`node scripts/readme/build.mjs\` and commit \`README.md\` and \`${ASSETS}/\` with it; CI fails while they are out of date. Changes land through pull requests, and a merge to \`main\` deploys the site.

Spotted an error in an entry? [Open an issue](https://github.com/ryanportfolio/SafeAI.Watch/issues) with the entry's title and a source that shows the correction.

## What the project holds to

- Every entry links its original source.
- Each entry separates what happened, what the evidence shows and what remains uncertain.
- No invented incidents, numbers or quotes. The site's illustrations are conceptual and carry no data; the chart at the top of this README is the exception, drawn from the record.
- No third-party trackers or analytics.

## Layout

| Path | Holds |
|---|---|
| \`src/pages/\` | The site's pages, built by [Astro](https://astro.build) as static HTML |
| \`src/data/\` | The record and its build-time checks |
| \`src/scripts/visuals/\` | The homepage's WebGL visuals |
| \`src/scripts/film/\`, \`film/\` | The About page film and its script |
| \`scripts/film/\` | The film's script check (\`npm run film:lint\`) and video export |
| \`scripts/brand/\` | The logo, icons and font subset (\`npm run brand\`) |
| \`scripts/readme/\` | This README and its art |

## Licence

Code is under the [MIT licence](LICENSE). Entries summarise and quote their sources; quoted material belongs to its authors. The bundled fonts (Geist, Geist Mono, Newsreader) are under the SIL Open Font License; their texts are in [\`LICENSES/\`](LICENSES).
`;
}

/** Offline invariants of a built README. Returns a list of failures. */
export function checkReadme(md, facts, root = ROOT) {
  const bad = [];
  if (!md.startsWith(MARKER)) bad.push('generated marker missing from line 1');
  if (/<a\b[^>]*>\s*<picture>/.test(md)) bad.push('a <picture> is wrapped in <a>; GitHub drops its <source> variants');
  for (const need of ['## Run it locally', 'npm ci', 'npm run dev', '## Licence', '## Add or correct an entry']) {
    if (!md.includes(need)) bad.push(`required text missing: ${need}`);
  }
  for (const link of [SITE, 'LICENSE', 'LICENSES', 'src/data/events.json', facts.latest.url]) {
    if (!md.includes(`](${link})`) && !md.includes(`href="${link}"`)) bad.push(`required link missing: ${link}`);
  }
  for (const m of md.matchAll(/(?:src|srcset)="([^"]+)"/g)) {
    if (!fs.existsSync(path.join(root, m[1]))) bad.push(`missing asset ${m[1]}`);
  }
  for (const m of md.matchAll(/\]\((?!https?:|#)([^)]+)\)/g)) {
    if (!fs.existsSync(path.join(root, m[1]))) bad.push(`local link target missing: ${m[1]}`);
  }
  return bad;
}
