import { collectFacts } from "./facts.mjs";
import { esc, writeText } from "./lib.mjs";

const facts = collectFacts();
const marker = "<!-- generated by scripts/readme/build.mjs. do not edit by hand. -->";

function picture(name, alt) {
  return `<picture>
<source media="(max-width: 500px) and (prefers-color-scheme: dark)" srcset="assets/readme/${name}-narrow-dark.svg">
<source media="(max-width: 500px)" srcset="assets/readme/${name}-narrow-light.svg">
<source media="(prefers-color-scheme: dark)" srcset="assets/readme/${name}-dark.svg">
<img alt="${esc(alt)}" src="assets/readme/${name}-light.svg" width="100%">
</picture>`;
}

function skillLists() {
  const sections = facts.groups.map((group) => {
    const skills = facts.skills.filter((skill) => skill.group === group.id);
    const rows = skills.map((skill) => `- [\`${skill.name}\`](.claude/skills/${skill.name}/SKILL.md) · ${skill.description}`).join("\n");
    return `### ${group.label.toLowerCase()} · ${skills.length}\n\n${rows}`;
  }).join("\n\n");
  return `<!-- skill-list:start -->\n${sections}\n<!-- skill-list:end -->`;
}

const readme = `${marker}

${picture("boot", `Harness Firmware boots with ${facts.skillCount} skills, ${facts.referenceFileCount} project-memory files, and ${facts.runtimeCount} runtime boundaries ready.`)}

A repository starter for **Claude Code and Codex**. Harness Firmware gives both agents versioned instructions, durable project memory, reusable skills, and workflows for testing and independent review.

Keep project decisions and pitfalls with the code. Carry useful lessons into the next session. Review changes before carrying them into another repository.

[Install the skills or start a repository](#quickstart).

## quickstart

Use the **skills-only plugin** for an existing Claude Code repository. Use the **full template** for a new repository or Codex support.

### existing repository · Claude Code plugin

Run these commands inside Claude Code:

\`\`\`text
/plugin marketplace add ryanportfolio/Harness-Firmware
/plugin install claude-starter@claude-starter
\`\`\`

Then try \`/claude-starter:recall\` or \`/claude-starter:brainstorming plan the next feature\`. Plugin skills use the \`claude-starter\` namespace.

### new repository · full template

Create a repository with the kernel, hooks, committed memory, skills, and synchronization tools:

- GitHub: select **Use this template**, clone the new repository, then run Claude Code's \`/init-project\` command or ask Codex to use the \`init-project\` skill.
- From a cloned Harness Firmware checkout on macOS or Linux: \`bash bootstrap/new-claude-project.sh --name my-app --dest ~/code\`
- From a cloned checkout on Windows: double-click \`bootstrap/New-ClaudeProject.cmd\`.

In the created repository, run \`node .claude/scripts/doctor.mjs\`. Success means the doctor reports no failures. Then ask Claude Code or Codex to use \`recall\` before the first unfamiliar change.

[Open the complete setup guide](GUIDE.md#full-template) · [View validation runs](https://github.com/ryanportfolio/Harness-Firmware/actions/workflows/validate-template.yml)

## what the firmware adds

| Need | Workflow built into the repository |
| --- | --- |
| Remember the project | \`recall\` loads relevant committed facts, decisions, and pitfalls before unfamiliar work |
| Finish sustained work | \`long-horizon\` records progress and evidence across bounded rounds, with fresh audit context |
| Challenge a result | Independent and cross-vendor review skills check work through available agents or authenticated CLIs |
| Verify a claim | \`verify-this\` separates current checks, comparisons, and causal claims; \`perf-loop\` measures optimization against a baseline |
| Maintain skills | \`addskill\` handles creating, importing, updating, and installing skills with the resources each runtime needs |
| Improve the workflow | \`refine\` captures observed friction; \`sync-starter\` carries selected generic fixes between repositories |

These are agent instructions and supporting tools. Structural checks validate the package; actual execution still needs the appropriate model, tools, credentials, and evidence.

## the repository feedback loop

${picture("feedback", "Recall, work, verify, refine, and a reviewed repository change form a local loop. A separate human-approved sync can carry generic changes into future repositories.")}

The everyday loop is **recall → work → verify → refine → reviewed repository change → next task**. Project facts load before unfamiliar work. Verification captures evidence. \`refine\` turns observed friction into a small, reviewable change that strengthens the repository before the next task begins.

The dotted branch is separate: after human review, \`sync-starter\` can move a generic improvement into the template so future repositories begin with it. Keeping the lesson local remains the default.

## two runtimes, explicit ownership

${picture("runtime", `${facts.skillCount} Claude Code skills and ${facts.codexSkillCount} Codex skills share project memory. Codex has ${facts.codexNativeCount} native workflows and ${facts.codexAdapterCount} generated adapters.`)}

**${facts.skillCount} Claude Code skills · ${facts.codexSkillCount} Codex skills · ${facts.codexNativeCount} native Codex workflows · ${facts.codexAdapterCount} adapters**

- **Claude Code:** reads \`CLAUDE.md\`, \`.claude/skills/\`, and hooks for canonical playbooks and Claude-specific startup behavior.
- **Codex:** reads \`AGENTS.md\` and \`.agents/skills/\` for standalone Codex workflows and generated adapters with explicit capability and safety boundaries. [Skill ownership and personal copies](docs/codex-skills.md) explains how they are maintained.

Both runtimes read the committed project topics under \`.claude/reference/\`. Shared workflows live under \`.claude/skills/\`; standalone Codex workflows live under \`.agents/skills/\`.

## ${facts.skillCount} workflows, loaded when called

**${facts.tierCounts.core} core · ${facts.tierCounts.discipline} discipline · ${facts.tierCounts.specialist} specialist**

Only names and routing descriptions sit in the repository's generated skill index. Full workflow bodies stay on demand. The diagram's byte figures are a repository source-file estimate, not total runtime context; [the guide documents the measurement](GUIDE.md#measure-the-always-loaded-layer).

<details>
<summary><strong>Click to open the generated skill memory map</strong></summary>

${picture("skills", `A memory map of ${facts.skillCount} on-demand workflows grouped into ${facts.tierCounts.core} core, ${facts.tierCounts.discipline} discipline, and ${facts.tierCounts.specialist} specialist skills.`)}

</details>

<details>
<summary><strong>Click to browse all ${facts.skillCount} skills</strong></summary>

${skillLists()}

</details>

## checked on every change

The validation workflow checks shell and PowerShell entry points, generated adapters, native skill propagation, required resources, intended runtime coverage, retired entrypoints, the Windows project generator, and this README's generated facts and assets. [Inspect the CI runs](https://github.com/ryanportfolio/Harness-Firmware/actions/workflows/validate-template.yml).

The [capability manifest](.agents/skill-capabilities.json) records ownership and intended coverage independently of discovery. [Maintenance guidance](docs/codex-skills.md) covers native updates, disabled skills, and personal copies.

Run the local health check:

\`\`\`bash
node .claude/scripts/doctor.mjs
\`\`\`

## documentation

- [Setup and operating guide](GUIDE.md)
- [Contribution process](CONTRIBUTING.md)
- [Release history](CHANGELOG.md)
- [Skill provenance](.claude/skills/PROVENANCE.md)
- [MIT license](LICENSE)
`;

writeText("README.md", readme);
process.stdout.write("Generated README.md.\n");
